title: 照片集
subtitle: Take Photo Think Seriously
description: 拿起相机，认真思考
cover: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/IMG_7586.4e91my1ve140.17iz0sa56gik.webp'
author: lfkdsk

footer_logo: 
  use: self
  self:
    link: 'https://lfkdsk.github.io/'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://lfkdsk.github.io/gallery
root: /gallery

photography_page:
  slogan: true
  slogan_descr: 'The moments when I pressed the shutter, the moments are forever.'
  travel_slogan: true
  travel_slogan_descr: 'Travel all over the world ~'

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: G-8TMSDJG47Q

nav:
  地图:
    link: /gallery/location
    icon: local-two
  归档: 
    link: https://lfkdsk.github.io
    icon: inbox
  随机:
    link: /gallery/random
    icon: pic
    
thumbnail_url: https://cdn.jsdelivr.net/gh/lfkdsk/gallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/lfkdsk/gallery@master
